# Generated by Django 4.2.17 on 2025-01-06 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.SmallAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.SmallAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prerequisite', models.CharField(blank=True, help_text='Classes needed before a student can apply to the course. \n        Please enter full name of course', max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.SmallAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='apclass',
            options={'verbose_name': 'AP'},
        ),
        migrations.RemoveField(
            model_name='apclass',
            name='is_active',
        ),
        migrations.AddField(
            model_name='apclass',
            name='benefits',
            field=models.TextField(default='', help_text='Enter new benefits on a new line'),
        ),
        migrations.AddField(
            model_name='apclass',
            name='description',
            field=models.TextField(default='', help_text='Description of class'),
        ),
        migrations.AddField(
            model_name='apclass',
            name='is_offered',
            field=models.BooleanField(default=True, help_text='Check this box if class will be offered for the upcoming school year'),
        ),
        migrations.AddField(
            model_name='apclass',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique link generated based on class name. \n        Example: classes/calculus instead of classes/9', unique=True),
        ),
        migrations.AddField(
            model_name='apclass',
            name='student_resource',
            field=models.URLField(blank=True, default='', help_text='Link for students to access helpful resources of this class if there are any'),
        ),
        migrations.AlterField(
            model_name='apclass',
            name='id',
            field=models.SmallAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='apclass',
            name='name',
            field=models.CharField(help_text="Do not need to put 'AP' before the class name", max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='apclass',
            name='grade_level',
            field=models.ManyToManyField(to='classes.gradelevel'),
        ),
        migrations.AddField(
            model_name='apclass',
            name='prerequisite',
            field=models.ManyToManyField(to='classes.prerequisite'),
        ),
        migrations.AddField(
            model_name='apclass',
            name='subject',
            field=models.ForeignKey(default='1', help_text='Choose the subject that best relates to this class', on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='classes.subject'),
        ),
    ]
