# Generated by Django 4.2.17 on 2025-01-07 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_gradelevel_prerequisite_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apclass',
            name='benefits',
            field=models.TextField(blank=True, help_text='Enter new benefits on a new line'),
        ),
        migrations.AlterField(
            model_name='apclass',
            name='prerequisite',
            field=models.ManyToManyField(blank=True, to='classes.prerequisite'),
        ),
    ]
