# Generated by Django 4.2.17 on 2024-12-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_apclass_id_alter_apclass_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apclass',
            options={'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterField(
            model_name='apclass',
            name='name',
            field=models.CharField(help_text="Do not need to put 'AP' before the class name.", max_length=200, unique=True),
        ),
    ]
