# Generated by Django 4.2.17 on 2024-12-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_apclass_options_alter_apclass_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='apclass',
            name='slug',
            field=models.SlugField(default='', editable=False),
        ),
        migrations.AlterField(
            model_name='apclass',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
