# Generated by Django 4.2.17 on 2024-12-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_apclass_slug_alter_apclass_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apclass',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
