# Generated by Django 4.2.17 on 2024-12-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_alter_apclass_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apclass',
            options={'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterField(
            model_name='apclass',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Specifies if the class is currently offered for the school year'),
        ),
        migrations.AlterField(
            model_name='apclass',
            name='name',
            field=models.CharField(help_text="Do not need to put 'AP' before the class name", max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='apclass',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text='Unique link generation based on AP class name', unique=True),
        ),
    ]
