# Generated by Django 4.2.17 on 2024-12-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0010_alter_apclass_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apclass',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Check if class is offered for the current school year'),
        ),
    ]
