# Generated by Django 4.2.17 on 2024-12-19 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0011_alter_apclass_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apclass',
            options={'verbose_name': 'AP'},
        ),
    ]
