# Generated by Django 4.2.17 on 2024-12-20 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0012_alter_apclass_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apclass',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
