# Generated by Django 4.2.17 on 2024-12-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0014_remove_apclass_is_active_apclass_is_offered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apclass',
            name='is_offered',
            field=models.BooleanField(default=True, help_text='Check this box if class is offered for the current school year'),
        ),
    ]
