# Generated by Django 4.2.17 on 2024-12-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0015_alter_apclass_is_offered'),
    ]

    operations = [
        migrations.AddField(
            model_name='apclass',
            name='description',
            field=models.TextField(default='', help_text='Description of class'),
        ),
    ]
