# Generated by Django 4.2.17 on 2024-12-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0016_apclass_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('grade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=50)),
            ],
        ),
    ]
