# Generated by Django 4.2.17 on 2024-12-20 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0017_gradelevel_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='apclass',
            name='subject',
            field=models.ForeignKey(default='1', help_text='Choose the subject that best relates to this class', on_delete=django.db.models.deletion.PROTECT, to='classes.subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject',
            field=models.CharField(max_length=50),
        ),
    ]
