# Generated by Django 4.2.17 on 2024-12-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0019_apclass_available_to_alter_apclass_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apclass',
            name='id',
            field=models.SmallAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gradelevel',
            name='id',
            field=models.SmallAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.SmallAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
