# Generated by Django 4.2.17 on 2024-12-21 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0020_alter_apclass_id_alter_gradelevel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apclass',
            name='is_offered',
            field=models.BooleanField(default=True, help_text='Check this box if class will be offered for the upcoming school year'),
        ),
    ]
