# Generated by Django 4.2.17 on 2024-12-21 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0021_alter_apclass_is_offered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apclass',
            old_name='available_to',
            new_name='grade_levels',
        ),
        migrations.AddField(
            model_name='apclass',
            name='student_resource',
            field=models.URLField(help_text='Link for students to access helpful resources of this class if there are any', null=True),
        ),
        migrations.AlterField(
            model_name='apclass',
            name='subject',
            field=models.ForeignKey(default='1', help_text='Choose the subject that best relates to this class', on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='classes.subject'),
        ),
        migrations.CreateModel(
            name='ApClassPrereq',
            fields=[
                ('id', models.SmallAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prerequisite', models.CharField(default='', help_text='Classes needed before a student can apply to the course. \n                                                                                        Please enter full name of course', max_length=50)),
                ('ap', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='prereqs', to='classes.apclass')),
            ],
            options={
                'verbose_name': 'Pre-requisite',
            },
        ),
        migrations.CreateModel(
            name='ApClassBenefit',
            fields=[
                ('id', models.SmallAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit', models.CharField(default='', help_text='character limit: 75', max_length=75)),
                ('ap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefit', to='classes.apclass')),
            ],
        ),
    ]
