# Generated by Django 4.2.17 on 2024-12-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0022_rename_available_to_apclass_grade_levels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apclass',
            name='grade_levels',
            field=models.ManyToManyField(related_name='grade_level', to='classes.gradelevel'),
        ),
        migrations.AlterField(
            model_name='apclass',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique link generated based on class name. \n                                                                              Example: classes/calculus instead of classes/9', unique=True),
        ),
        migrations.AlterField(
            model_name='apclass',
            name='student_resource',
            field=models.URLField(blank=True, default='', help_text='Link for students to access helpful resources of this class if there are any'),
        ),
        migrations.AlterField(
            model_name='apclassbenefit',
            name='benefit',
            field=models.CharField(blank=True, help_text='character limit: 75', max_length=75, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='apclassprereq',
            name='prerequisite',
            field=models.CharField(blank=True, help_text='Classes needed before a student can apply to the course. \n                                                                                        Please enter full name of course', max_length=50, null=True, unique=True),
        ),
    ]
