# Generated by Django 4.2.17 on 2024-12-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0024_alter_apclass_grade_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apclass',
            name='grade_levels',
            field=models.ManyToManyField(related_name='grades', to='classes.gradelevel'),
        ),
    ]
