# Generated by Django 4.2.17 on 2024-12-23 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0026_alter_apclass_grade_levels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apclass',
            old_name='grade_levels',
            new_name='grade_level',
        ),
    ]
