# Generated by Django 4.2.17 on 2024-12-24 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0027_rename_grade_levels_apclass_grade_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apclassbenefit',
            name='ap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='classes.apclass'),
        ),
    ]
