# Generated by Django 4.2.17 on 2024-12-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.SmallAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Max character limit: 150', max_length=150, verbose_name='Event Name')),
                ('location', models.CharField(help_text='Please put formal name. Max character limit: 75', max_length=75, verbose_name='Event Location')),
                ('meeting_link', models.URLField(default='', blank=True, help_text='Online meeting link. Can be left empty')),
                ('description', models.TextField()),
                ('date', models.DateTimeField(verbose_name='Event Date and Start Time')),
                ('duration', models.DurationField(help_text='Estimated length of event')),
                ('resource', models.URLField(default='', blank=True, help_text='Public resource link for students, \n                                                                                      parents, and faculty that cannot make \n                                                                                      it to event. Can be left empty', verbose_name='Resource Link')),
            ],
        ),
    ]
