# Generated by Django 4.2.17 on 2025-01-01 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(default='12:30', help_text='Time that the event starts', verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(help_text='Date Event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='resource',
            field=models.URLField(blank=True, default='', help_text='Public resource link for students, \n                                                                    parents, and faculty that cannot make \n                                                                    it to event. Can be left empty'),
        ),
    ]
