# Generated by Django 4.2.17 on 2025-01-01 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_time_alter_event_date_alter_event_resource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='duration',
        ),
        migrations.AddField(
            model_name='event',
            name='end',
            field=models.TimeField(default='12:00', help_text='Estimated time event will end', verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(default='12:00', help_text='Time that the event starts', verbose_name='Start Time'),
        ),
    ]
