# Generated by Django 4.2.17 on 2025-01-05 05:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_duration_event_end_alter_event_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
        migrations.AddField(
            model_name='event',
            name='start',
            field=models.TimeField(default=datetime.time(19, 33, 44, 297207), help_text='Time that the event starts', verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.TimeField(default=datetime.time(19, 33, 44, 297207), help_text='Estimated time event will end', verbose_name='End Time'),
        ),
    ]
