# Generated by Django 4.2.17 on 2025-01-05 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_time_event_start_alter_event_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='', help_text='Unique link generated based on event name and year. Example: events/parent-night-2025 vs events/1', max_length=75),
        ),
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.TimeField(default=datetime.time(0, 0), help_text='Estimated time event will end', verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.TimeField(default=datetime.time(0, 0), help_text='Time that the event starts', verbose_name='Start Time'),
        ),
    ]
