name: Server Tests

on: 
    push:
      branches: 
        - main
      paths-ignore:
        - .github/**/*
        - ./README.md
        - client/**/*
        - public/**/*
    pull_request:
        branches: 
            - main
        paths-ignore: 
            - .github/**/*
            - ./README.md
            - client/**/*
            - public/**/*
    workflow_dispatch: 

jobs:
    run_tests: 
        name: Run Python Tests
        runs-on: ubuntu-latest
        

        steps:
            - uses: actions/checkout@v4
            
            - uses: actions/setup-python@v5
              with: 
                python-version: '3.11'

            - name: Download Python Dependencies
              run: | 
                python -m pip install --upgrade pip
                pip install pipenv
                pipenv install -d --ignore-pipfile

            - name: Run Tests
              env: 
                SECRET_KEY: ${{ secrets.SECRET_KEY }}
              run: pipenv run python manage.py test
              working-directory: ./server
            
                